server:
  port: 8080

inception:
  application:
    data-source:
      class-name: org.h2.jdbcx.JdbcDataSource
      url: jdbc:h2:mem:application;MODE=DB2;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      min-pool-size: 5
      max-pool-size: 10
  oauth2:
    authorization-server:
      jwt:
        private-key-location: classpath:META-INF/oauth2-jwt-key
        public-key-location: classpath:META-INF/oauth2-jwt-key.pub

spring:
  application:
    name: demo
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:META-INF/oauth2-jwt-key.pub
